package com.redhat.patientrecord;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MedicalReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String ssn;
	private java.util.Date erAdmissionDate;
	private java.lang.String erTag;
	private java.util.Date erDischargeDate;
	private java.lang.String erFirstDiagnosis;

	private java.util.List<com.redhat.patientrecord.Checkup> erCheckups;

	public MedicalReport() {
	}

	public java.lang.String getSsn() {
		return this.ssn;
	}

	public void setSsn(java.lang.String ssn) {
		this.ssn = ssn;
	}

	public java.util.Date getErAdmissionDate() {
		return this.erAdmissionDate;
	}

	public void setErAdmissionDate(java.util.Date erAdmissionDate) {
		this.erAdmissionDate = erAdmissionDate;
	}

	public java.lang.String getErTag() {
		return this.erTag;
	}

	public void setErTag(java.lang.String erTag) {
		this.erTag = erTag;
	}

	public java.util.Date getErDischargeDate() {
		return this.erDischargeDate;
	}

	public void setErDischargeDate(java.util.Date erDischargeDate) {
		this.erDischargeDate = erDischargeDate;
	}

	public java.lang.String getErFirstDiagnosis() {
		return this.erFirstDiagnosis;
	}

	public void setErFirstDiagnosis(java.lang.String erFirstDiagnosis) {
		this.erFirstDiagnosis = erFirstDiagnosis;
	}

	public java.util.List<com.redhat.patientrecord.Checkup> getErCheckups() {
		return this.erCheckups;
	}

	public void setErCheckups(
			java.util.List<com.redhat.patientrecord.Checkup> erCheckups) {
		this.erCheckups = erCheckups;
	}

	public MedicalReport(java.lang.String ssn, java.util.Date erAdmissionDate,
			java.lang.String erTag, java.util.Date erDischargeDate,
			java.lang.String erFirstDiagnosis,
			java.util.List<com.redhat.patientrecord.Checkup> erCheckups) {
		this.ssn = ssn;
		this.erAdmissionDate = erAdmissionDate;
		this.erTag = erTag;
		this.erDischargeDate = erDischargeDate;
		this.erFirstDiagnosis = erFirstDiagnosis;
		this.erCheckups = erCheckups;
	}

}