package com.redhat.patientrecord.service;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MinistryOfHealthNotification implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MinistryOfHealthNotification() {}
    
    public String sendNotification(String text) {
        String message = "Message received :: " + text + "!";
        System.out.println(message);
        return message;
    }




}